# Generated by Django 4.2.6 on 2023-12-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedemand',
            name='completion_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicedemand',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicedemand',
            name='exact_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicedemand',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='servicedemand',
            name='tel_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
