# Generated by Django 4.2.6 on 2023-12-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_servicedemand_completion_time_servicedemand_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicedemand',
            name='country',
        ),
        migrations.RemoveField(
            model_name='servicedemand',
            name='exact_address',
        ),
        migrations.RemoveField(
            model_name='servicedemand',
            name='tel_number',
        ),
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
